# Generated by Django 4.1.2 on 2022-10-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
