# Generated by Django 4.1.2 on 2022-10-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0002_expense_created_at_expense_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="name",
            new_name="title",
        ),
    ]
